In [49]:
from positive_TN_src import *

In [58]:
a = np.load("all_one.npz")
a["avg_table"]

array([[0.25801368, 0.22041754,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan],
       [0.40765961, 0.35428652,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan],
       [0.28641324,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan]])

In [38]:
a = np.load("all_one.npz")
a = dict(a)
a["avg_table"][0, 0] = None
np.savez("all_one2.npz", *a)

In [44]:
a2 = np.load("all_one2.npz", allow_pickle=True)
a2["std_table"]

array([[0.14988119, 0.1425121 , 0.1818244 , 0.1372459 , 0.16241655,
        0.08380812, 0.13705615, 0.05713321, 0.01204659, 0.01555653],
       [0.17222457, 0.18519707, 0.18900978, 0.18153629, 0.14914769,
        0.16408401, 0.13501853, 0.02931223, 0.06528073, 0.00715327],
       [0.13882317, 0.18191752, 0.1840572 , 0.19983106, 0.14734114,
        0.18470258, 0.08797854, 0.02776063, 0.00798296, 0.00584057]])

In [46]:
a = np.array([[None for _ in range(10)] for _ in range(3)])
a[0, 0] = 1
a

array([[1, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None]],
      dtype=object)