In [22]:
from src.stats_model import *
import scipy.linalg as la

In [90]:
def largest_eigvec(M):
    w, vr = la.eig(M)
    v = vr[:, np.argmax(w)]
    return v

d = 10000
mu = 1

T = SM_TI_site(d, mu)

L = delta(7, 3)
stop = False
while not stop:
    M1 = np.einsum("ijk,opkn,lmn->ioljpm", L, T, L).reshape((7**3, 7**3))
    E = largest_eigvec(M1).reshape((7, 7, 7)).swapaxes(0, 1)

    M2 = np.einsum("ijk,ilm->jlkm", E, E).reshape((7**2, 7**2))
    C = largest_eigvec(M2).reshape((7, 7))
                                
    M3 = np.einsum("ijk,ilop,lmn->jomkpn", E, T, E).reshape((7**3, 7**3))
    LC = largest_eigvec(M3).reshape((7, 7, 7))
    new_L = np.einsum("ijk,kl->ijl", LC, la.pinv(C)).swapaxes(1, 2)
    diff = np.sum(abs(new_L - L))
    print(diff)
    if diff < 1E-5:
        stop = True
    L = new_L

6.010127031412342
3.04643613230867e-10


In [91]:
np.nonzero(L)

(array([5, 5, 5, 5, 5, 5, 5], dtype=int64),
 array([5, 5, 5, 5, 5, 5, 5], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6], dtype=int64))

In [93]:
L[5, 5, :]

array([1.25078154e-07+0.j, 5.00100020e-03+0.j, 3.75050018e-05+0.j,
       3.75050018e-05+0.j, 2.50098471e-05+0.j, 9.99974989e-01+0.j,
       5.00087518e-03+0.j])

In [94]:
C

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])